apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - quarantine-networkpolicy.yaml
  - rbac.yaml
  - contract-configmap.yaml
  - engine-daemonset.yaml
  - research-agent-demo.yaml
